"""baseline schema

Revision ID: 88ae989a5ca0
Revises: 
Create Date: 2026-07-26 15:20:12.010633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ae989a5ca0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_budgets_department'), 'department_budgets', ['department'], unique=False)
    op.create_index('ix_department_budgets_dept_year', 'department_budgets', ['department', 'year'], unique=True)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector_json', sa.JSON(), nullable=False),
    sa.Column('text_preview', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embeddings_entity', 'embeddings', ['entity_type', 'entity_id'], unique=True)
    op.create_index('ix_embeddings_type_model', 'embeddings', ['entity_type', 'model'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index('ix_employees_dept_status', 'employees', ['department', 'status'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('vector_json', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_category', 'knowledge_entries', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('ministry', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_backup_codes', sa.JSON(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_ministry'), 'users', ['ministry'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_ministry', 'users', ['role', 'ministry'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('budget_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('spent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['department_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_expenses_budget_id'), 'budget_expenses', ['budget_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_candidates_user_id', 'candidates', ['user_id'], unique=False)
    op.create_table('career_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_position', sa.String(length=200), nullable=True),
    sa.Column('target_position', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('skills_to_develop', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_plans_status', 'career_plans', ['status'], unique=False)
    op.create_index(op.f('ix_career_plans_user_id'), 'career_plans', ['user_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('required_experience_years', sa.Float(), nullable=True),
    sa.Column('required_education_level', sa.String(length=20), nullable=True),
    sa.Column('weight_skills', sa.Float(), nullable=False),
    sa.Column('weight_experience', sa.Float(), nullable=False),
    sa.Column('weight_education', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_offers_active_created', 'job_offers', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_offers_is_active'), 'job_offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_offers_title'), 'job_offers', ['title'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_offer_id', sa.UUID(), nullable=False),
    sa.Column('cv_file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_candidate_job', 'applications', ['candidate_id', 'job_offer_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('job_offer_id', sa.UUID(), nullable=True),
    sa.Column('predicted_salary', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('initial_offer', sa.Float(), nullable=False),
    sa.Column('final_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rounds_count', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_job_id'), 'negotiations', ['job_id'], unique=False)
    op.create_index('ix_negotiations_job_status', 'negotiations', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_negotiations_status'), 'negotiations', ['status'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_offer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_jobs_user_job', 'saved_jobs', ['user_id', 'job_offer_id'], unique=True)
    op.create_table('candidate_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('job_offer_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('ix_candidate_scores_application_id', 'candidate_scores', ['application_id'], unique=False)
    op.create_index('ix_candidate_scores_candidate_id', 'candidate_scores', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_scores_job_offer_id', 'candidate_scores', ['job_offer_id'], unique=False)
    op.create_index('ix_candidate_scores_job_rank', 'candidate_scores', ['job_offer_id', 'rank'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'STAGE', 'ALTERNANCE', name='contract_type'), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_period_months', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('employee_birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_cin', sa.String(length=30), nullable=True),
    sa.Column('employee_cin_issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SIGNED', 'ACTIVE', 'DECLINED', 'EXPIRED', name='contract_status'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signer_name', sa.String(length=200), nullable=True),
    sa.Column('signer_ip', sa.String(length=45), nullable=True),
    sa.Column('signer_user_agent', sa.String(length=400), nullable=True),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('certificate_id', sa.String(length=40), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('ix_contracts_application', 'contracts', ['application_id'], unique=False)
    op.create_index('ix_contracts_status', 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_token'), 'contracts', ['token'], unique=True)
    op.create_table('cv_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=False),
    sa.Column('extracted_experience_years', sa.Float(), nullable=True),
    sa.Column('extracted_education_level', sa.String(length=20), nullable=True),
    sa.Column('extracted_job_titles', sa.JSON(), nullable=False),
    sa.Column('extracted_keywords', sa.JSON(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('ix_cv_analyses_application_id', 'cv_analyses', ['application_id'], unique=False)
    op.create_index('ix_cv_analyses_candidate_id', 'cv_analyses', ['candidate_id'], unique=False)
    op.create_table('cv_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cv_chunks_app_idx', 'cv_chunks', ['application_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_cv_chunks_application_id'), 'cv_chunks', ['application_id'], unique=False)
    op.create_table('interview_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='invitation_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_slot_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_slot_id'], ['interview_slots.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_invitations_status'), 'interview_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_interview_invitations_token'), 'interview_invitations', ['token'], unique=True)
    op.create_index('ix_invitations_app_status', 'interview_invitations', ['application_id', 'status'], unique=False)
    op.create_table('negotiation_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_negotiation_rounds_neg_round', 'negotiation_rounds', ['negotiation_id', 'round_number'], unique=False)
    op.create_index(op.f('ix_negotiation_rounds_negotiation_id'), 'negotiation_rounds', ['negotiation_id'], unique=False)
    op.create_table('interview_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['interview_invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_slots_is_selected'), 'interview_slots', ['is_selected'], unique=False)
    op.create_index(op.f('ix_interview_slots_start_at'), 'interview_slots', ['start_at'], unique=False)
    op.create_index('ix_slots_invitation', 'interview_slots', ['invitation_id'], unique=False)
    op.create_index('ix_slots_start_selected', 'interview_slots', ['start_at', 'is_selected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slots_start_selected', table_name='interview_slots')
    op.drop_index('ix_slots_invitation', table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_start_at'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_is_selected'), table_name='interview_slots')
    op.drop_table('interview_slots')
    op.drop_index(op.f('ix_negotiation_rounds_negotiation_id'), table_name='negotiation_rounds')
    op.drop_index('ix_negotiation_rounds_neg_round', table_name='negotiation_rounds')
    op.drop_table('negotiation_rounds')
    op.drop_index('ix_invitations_app_status', table_name='interview_invitations')
    op.drop_index(op.f('ix_interview_invitations_token'), table_name='interview_invitations')
    op.drop_index(op.f('ix_interview_invitations_status'), table_name='interview_invitations')
    op.drop_table('interview_invitations')
    op.drop_index(op.f('ix_cv_chunks_application_id'), table_name='cv_chunks')
    op.drop_index('ix_cv_chunks_app_idx', table_name='cv_chunks')
    op.drop_table('cv_chunks')
    op.drop_index('ix_cv_analyses_candidate_id', table_name='cv_analyses')
    op.drop_index('ix_cv_analyses_application_id', table_name='cv_analyses')
    op.drop_table('cv_analyses')
    op.drop_index(op.f('ix_contracts_token'), table_name='contracts')
    op.drop_index('ix_contracts_status', table_name='contracts')
    op.drop_index('ix_contracts_application', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_candidate_scores_job_rank', table_name='candidate_scores')
    op.drop_index('ix_candidate_scores_job_offer_id', table_name='candidate_scores')
    op.drop_index('ix_candidate_scores_candidate_id', table_name='candidate_scores')
    op.drop_index('ix_candidate_scores_application_id', table_name='candidate_scores')
    op.drop_table('candidate_scores')
    op.drop_index('ix_saved_jobs_user_job', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_negotiations_status'), table_name='negotiations')
    op.drop_index('ix_negotiations_job_status', table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_job_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_candidate_job', table_name='applications')
    op.drop_table('applications')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_job_offers_title'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_is_active'), table_name='job_offers')
    op.drop_index('ix_job_offers_active_created', table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_career_plans_user_id'), table_name='career_plans')
    op.drop_index('ix_career_plans_status', table_name='career_plans')
    op.drop_table('career_plans')
    op.drop_index('ix_candidates_user_id', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_budget_expenses_budget_id'), table_name='budget_expenses')
    op.drop_table('budget_expenses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_ministry', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_ministry'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_knowledge_category', table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index('ix_employees_dept_status', table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_embeddings_type_model', table_name='embeddings')
    op.drop_index('ix_embeddings_entity', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_department_budgets_dept_year', table_name='department_budgets')
    op.drop_index(op.f('ix_department_budgets_department'), table_name='department_budgets')
    op.drop_table('department_budgets')
    # ### end Alembic commands ###
